"""add org_id

Revision ID: b48c7e0c4243
Revises: 
Create Date: 2026-04-12 14:03:52.930303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48c7e0c4243'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.String(), nullable=False))
    op.add_column('items', sa.Column('type', sa.String(), nullable=False))
    op.add_column('items', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_type'), 'items', ['type'], unique=False)
    op.create_foreign_key(None, 'items', 'organizations', ['organization_id'], ['id'])
    op.drop_column('items', 'title')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.add_column('items', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_type'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.drop_column('items', 'organization_id')
    op.drop_column('items', 'type')
    op.drop_column('items', 'name')
    # ### end Alembic commands ###
