"""add role image_url notifications

Revision ID: fea0b972ea5c
Revises: 9ae477fc56ed
Create Date: 2026-05-08 16:32:42.017493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fea0b972ea5c'
down_revision: Union[str, Sequence[str], None] = '9ae477fc56ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('invite_codes', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invite_codes', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invite_codes', 'max_uses',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invite_codes', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invite_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('invite_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('items', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='user'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('items', 'image_url')
    op.alter_column('invite_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invite_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invite_codes', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invite_codes', 'max_uses',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invite_codes', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invite_codes', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
